language: bash
install:
  - sudo apt-get update
  - sudo apt-get install gettext
  - wget http://pology.nedohodnik.net/release/pology-0.12.tar.bz2
  - tar jxf pology-0.12.tar.bz2
script:
  - PATH=$PATH$:pology-0.12/
  - export PATH
  - ./check.sh
